In [1]:
import pandas as pd
import numpy as np
import joblib

# PD model trained and saved in notebook 02
pd_model = joblib.load('../pd_model_xgb.pkl')

# Reload the dataset (same columns as in the PD model)
df = pd.read_csv('../data/accepted_2007_to_2018Q4.csv.gz', low_memory=False)

cols = ['funded_amnt', 'term', 'int_rate', 'grade', 'emp_length',
        'home_ownership', 'annual_inc', 'purpose', 'dti', 'loan_status']
df = df[cols]

# Keep loans with a final outcome (same criterion as in the PD model)
df = df[df['loan_status'].isin(['Fully Paid', 'Charged Off'])].copy()

print(f"Total loans: {len(df):,}")

Total loans: 1,345,310

In [2]:
# Prepare the features exactly as in notebook 02: the saved model expects the same columns, in the same order
features = ['funded_amnt', 'term', 'int_rate', 'grade', 'emp_length',
            'home_ownership', 'annual_inc', 'purpose', 'dti']

X_full = df[features].copy()
X_full = X_full.rename(columns={'funded_amnt': 'loan_amnt'})  # the model was trained with this column name

X_full['term'] = X_full['term'].str.extract(r'(\d+)').astype(float)

emp_map = {'< 1 year': 0, '1 year': 1, '2 years': 2, '3 years': 3, '4 years': 4,
           '5 years': 5, '6 years': 6, '7 years': 7, '8 years': 8, '9 years': 9, '10+ years': 10}
X_full['emp_length'] = X_full['emp_length'].map(emp_map)

grade_map = {'A': 1, 'B': 2, 'C': 3, 'D': 4, 'E': 5, 'F': 6, 'G': 7}
X_full['grade'] = X_full['grade'].map(grade_map)

X_full = pd.get_dummies(X_full, columns=['home_ownership', 'purpose'], drop_first=True)

X_full['emp_length'] = X_full['emp_length'].fillna(X_full['emp_length'].median())
X_full['dti'] = X_full['dti'].fillna(X_full['dti'].median())

# Predicted probability of default (PD) for each loan.
# Note: the model was trained on 80% of these same loans, so this is partly in-sample
# and the portfolio average stays close to the historical default rate.
df['PD'] = pd_model.predict_proba(X_full)[:, 1]

df[['funded_amnt', 'grade', 'PD']].head()

   funded_amnt grade        PD
0       3600.0     C  0.115503
1      24700.0     C  0.255539
2      20000.0     B  0.171966
4      10400.0     F  0.371160
5      11950.0     C  0.224306

In [3]:
# LGD by grade, saved by notebook 03
import json
with open('../lgd_by_grade.json') as f:
    lgd_dict = json.load(f)

# Assign each loan the LGD of its grade
df['LGD'] = df['grade'].map(lgd_dict)

# EAD = Exposure at Default. Approximated with the original loan amount
df['EAD'] = df['funded_amnt']

# Expected loss per loan = PD x LGD x EAD
df['expected_loss'] = df['PD'] * df['LGD'] * df['EAD']

df[['funded_amnt', 'grade', 'PD', 'LGD', 'EAD', 'expected_loss']].head()

   funded_amnt grade        PD       LGD      EAD  expected_loss
0       3600.0     C  0.115503  0.469155   3600.0     195.079520
1      24700.0     C  0.255539  0.469155  24700.0    2961.214789
2      20000.0     B  0.171966  0.450974  20000.0    1551.046747
4      10400.0     F  0.371160  0.478732  10400.0    1847.937906
5      11950.0     C  0.224306  0.469155  11950.0    1257.551563

In [4]:
# Portfolio level: add up the loan-level expected losses
el_total = df['expected_loss'].sum()
ead_total = df['EAD'].sum()
el_ratio = el_total / ead_total * 100

print(f"Portfolio expected loss: ${el_total:,.2f}")
print(f"Portfolio exposure (EAD): ${ead_total:,.2f}")
print(f"Expected loss ratio: {el_ratio:.2f}%")

Portfolio expected loss: $1,952,791,340.44
Portfolio exposure (EAD): $19,388,011,250.00
Expected loss ratio: 10.07%